name: helpwave_service
description: A package for the helpwave services
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

  impulse:
    path: "../../apps/impulse"
  helpwave_proto_dart: ^0.29.0-01c8073.0
publish_to: none

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

