name: helpwave_service
description: A package for the helpwave services
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app

environment:
  sdk: '>=3.5.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  openid_client: ^0.4.7
  url_launcher: ^6.2.1
  flutter_secure_storage: 9.0.0
  jose: ^0.3.4
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

