name: helpwave_service
description: A package for the helpwave services
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app
publish_to: none

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  openid_client: ^0.4.7
  url_launcher: ^6.2.1
  flutter_secure_storage: 9.0.0
  jose: ^0.3.4
  logger: ^2.0.2+1
  helpwave_proto_dart: ^0.46.0-336429a
  grpc: ^3.2.4
  helpwave_util:
    path: "../helpwave_util"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  # flutter config
