name: helpwave
repository: https://github.com/helpwave/mobile-app
packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    exec: dart analyze .

  intl:
    run: melos exec --file-exists="./lib/main.dart" -- "flutter gen-l10n"

  build-apk:
    run: melos exec --file-exists="./lib/main.dart" "flutter build apk"

  build-ios:
    exec: melos exec --file-exists="./lib/main.dart" "flutter build ios --no-codesign"
