name: helpwave
repository: https://github.com/helpwave/mobile-app
packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    exec: dart analyze .

  intl:
    run: melos exec --dir-exists="../helpwave_localization" -- "flutter gen-l10n"

  build-apk:
    run: melos exec --dir-exists="../../apps" "flutter build apk"

  build-ios:
    exec: melos exec --dir-exists="../../apps" "flutter build ios --no-codesign"
