name: helpwave
repository: https://github.com/helpwave/mobile-app
packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    exec: melos exec -- "dart analyze ."

  intl:
    exec: melos exec --file-exists="l10n.yaml" -- "flutter gen-l10n && melos bootstrap"

  build-apk:
    exec: melos exec --file-exists="./lib/main.dart" "melos run intl && flutter build apk"

  build-ios:
    exec: melos exec --file-exists="./lib/main.dart" "melos run intl && flutter build ios --no-codesign"
