name: helpwave_melos
repository: https://github.com/helpwave/mobile-app
packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    run: melos exec -- "dart analyze ."

  intl:
    run: melos exec --file-exists="l10n.yaml" -- "flutter gen-l10n && melos bootstrap"

  build-tasks-apk:
    run: melos exec --scope="tasks" --file-exists="./lib/main.dart" "flutter build apk --debug"

  build-impulse-apk:
    run: melos exec --scope="impulse" --file-exists="./lib/main.dart" "flutter build apk --debug"

  build-tasks-ios:
    run: melos exec --scope="tasks" --file-exists="./lib/main.dart" "flutter build ios --no-codesign --debug"

  build-impulse-ios:
    run: melos exec --scope="impulse" --file-exists="./lib/main.dart" "flutter build ios --no-codesign --debug"

  build-tasks-aab:
    run: melos exec --scope="tasks" --file-exists="./lib/main.dart" "flutter build appbundle"

  build-impulse-aab:
    run: melos exec --scope="impulse" --file-exists="./lib/main.dart" "flutter build appbundle"
