name: helpwave_melos
repository: https://github.com/helpwave/mobile-app
packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    run: melos exec -- "dart analyze ."

  intl:
    run: melos exec --file-exists="l10n.yaml" -- "flutter gen-l10n && melos bootstrap"

  build-apk:
    run: melos exec --file-exists="./lib/main.dart" "flutter build apk --debug"

  build-ios:
    run: melos exec --file-exists="./lib/main.dart" "flutter build ios --no-codesign"

  build-aab:
    run: melos exec --file-exists="./lib/main.dart" "flutter build appbundle"
