name: helpwave_theme
description: The Theme of the helpwave app
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app

publish_to: none

environment:
  sdk: '>=3.5.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  helpwave_util:
    path: "../helpwave_util"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: lib/fonts/Space_Grotesk/SpaceGrotesk-VariableFont_wght.ttf
