name: helpwave_util
description: A package containing helpwave's utility classes
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app

publish_to: none

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
