name: helpwave_widget
description: A package containing some of helpwave's reusable widgets
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app

publish_to: none

environment:
  sdk: '>=3.5.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  helpwave_theme:
    path: "../helpwave_theme"
  helpwave_localization:
    path: "../helpwave_localization"
  helpwave_util:
    path: "../helpwave_util"
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
