name: helpwave_widget
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/helpwave/mobile-app

publish_to: none

environment:
  sdk: '>=3.1.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  helpwave_theme:
    path: "../helpwave_theme"
  helpwave_localization:
    path: "../helpwave_localization"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
